eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://discovery.inftfy-core-backend.svc.cluster.local:8761/eureka/}

logging:
    file:
        name: /tmp/admin-auth-gateway.log
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://35.200.208.111/realms/iNFTFy
                    jwk-set-uri: http://35.200.208.111/realms/iNFTFy/protocol/openid-connect/certs
