eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://35.200.208.111/auth/realms/inftfy
                    jwk-set-uri: http://35.200.208.111/auth/realms/inftfy/protocol/openid-connect/certs