eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://discovery:8761/eureka}

logging:
    file:
        name: /tmp/admin-auth-gateway.log
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://lemur-17.cloud-iam.com/auth/realms/inftfy
                    jwk-set-uri: https://lemur-17.cloud-iam.com/auth/realms/inftfy/protocol/openid-connect/certs
