logging:
    file:
        name: /tmp/adminservice.log
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://auth-server:9191/realms/iNftfy
                    jwk-set-uri: http://auth-server:9191/realms/iNftfy/protocol/openid-connect/certs
    datasource:
        url: jdbc:postgresql://postgres.inftfy-core-backend.svc.cluster.local:5432/inftfy
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
    jackson:
        serialization:
            fail-on-empty-beans: false
app:
    config:
        keycloak:
            server-url: http://${KCHOST}:${KCPORT}
            realm: iNFTFy
            clientId: realm-management
            client-secret: NbvxMAPrVj0MOaXi8eLetvbv2FY7PjvF