logging:
    file:
        name: /tmp/apigateway.log
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://auth.cognologix.in/realms/iNFTFy
                    jwk-set-uri: https://auth.cognologix.in/realms/iNFTFy/protocol/openid-connect/certs
    datasource:
        url: jdbc:postgresql://postgres.inftfy-core-backend.svc.cluster.local:5432/inftfy
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
    jackson:
        serialization:
            fail-on-empty-beans: false
app:
    config:
        keycloak:
            server-url: http://${KCHOST}:${KCPORT}
            realm: iNFTFy
            clientId: realm-management
            client-secret: qD5OpZLUzUKqqTjS5YJO6tIi2fixTvME 