logging:
    file:
        name: /tmp/blockchainservice.log
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    datasource:
        url: jdbc:postgresql://postgres.default.svc.cluster.local:5432/inftfy
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                show-sql: true
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        serialization:
            fail-on-empty-beans: false
            
wallet:
  testnetrpcurl: https://rpc-mumbai.maticvigil.com/
  testnetpk: 7b0a7c69ac5994a016fdbae128e89558cc55206542711ec84860b7cd362d5d27
  testnettoken: 0xbcd480f7839fe5b1174125dc7cd5a891c2cadda3
  testnetchainId: 80001
