
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://35.200.208.111/realms/iNFTFy
                    jwk-set-uri: http://35.200.208.111/realms/iNFTFy/protocol/openid-connect/certs

