logging:
    file:
        name: /tmp/nft-studio-service.log
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://35.200.208.111/auth/realms/inftfy
                    jwk-set-uri: http://35.200.208.111/auth/realms/inftfy/protocol/openid-connect/certs
    datasource:
        url: jdbc:postgresql://localhost:5432/inftfy
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
    jackson:
        serialization:
            fail-on-empty-beans: false