logging:
    file:
        name: /tmp/walletservice.log
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/inftfy
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
    jackson:
        serialization:
            fail-on-empty-beans: false